# Generated by Django 3.2.3 on 2021-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningText', models.TextField()),
                ('classlink', models.URLField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
