# Generated by Django 3.2.3 on 2021-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_joiningclass_classlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoClass',
        ),
        migrations.AlterField(
            model_name='joiningclass',
            name='joiningText',
            field=models.TextField(blank=True),
        ),
    ]
