# Generated by Django 3.2.3 on 2021-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210517_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningclass',
            name='noclasstext',
            field=models.TextField(blank=True),
        ),
    ]
