# Generated by Django 3.2.3 on 2021-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_joiningclass_noclasstext'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningclass',
            name='noticeText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
